/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ObservatorioRouteImport } from './routes/observatorio'
import { Route as NormativaRouteImport } from './routes/normativa'
import { Route as ConvocatoriasRouteImport } from './routes/convocatorias'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MesasIndexRouteImport } from './routes/mesas.index'
import { Route as MesasSlugRouteImport } from './routes/mesas.$slug'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservatorioRoute = ObservatorioRouteImport.update({
  id: '/observatorio',
  path: '/observatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const NormativaRoute = NormativaRouteImport.update({
  id: '/normativa',
  path: '/normativa',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvocatoriasRoute = ConvocatoriasRouteImport.update({
  id: '/convocatorias',
  path: '/convocatorias',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasIndexRoute = MesasIndexRouteImport.update({
  id: '/mesas/',
  path: '/mesas/',
  getParentRoute: () => rootRouteImport,
} as any)
const MesasSlugRoute = MesasSlugRouteImport.update({
  id: '/mesas/$slug',
  path: '/mesas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/normativa': typeof NormativaRoute
  '/observatorio': typeof ObservatorioRoute
  '/registro': typeof RegistroRoute
  '/mesas/$slug': typeof MesasSlugRoute
  '/mesas/': typeof MesasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/normativa': typeof NormativaRoute
  '/observatorio': typeof ObservatorioRoute
  '/registro': typeof RegistroRoute
  '/mesas/$slug': typeof MesasSlugRoute
  '/mesas': typeof MesasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/convocatorias': typeof ConvocatoriasRoute
  '/normativa': typeof NormativaRoute
  '/observatorio': typeof ObservatorioRoute
  '/registro': typeof RegistroRoute
  '/mesas/$slug': typeof MesasSlugRoute
  '/mesas/': typeof MesasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/convocatorias'
    | '/normativa'
    | '/observatorio'
    | '/registro'
    | '/mesas/$slug'
    | '/mesas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/convocatorias'
    | '/normativa'
    | '/observatorio'
    | '/registro'
    | '/mesas/$slug'
    | '/mesas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/convocatorias'
    | '/normativa'
    | '/observatorio'
    | '/registro'
    | '/mesas/$slug'
    | '/mesas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConvocatoriasRoute: typeof ConvocatoriasRoute
  NormativaRoute: typeof NormativaRoute
  ObservatorioRoute: typeof ObservatorioRoute
  RegistroRoute: typeof RegistroRoute
  MesasSlugRoute: typeof MesasSlugRoute
  MesasIndexRoute: typeof MesasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observatorio': {
      id: '/observatorio'
      path: '/observatorio'
      fullPath: '/observatorio'
      preLoaderRoute: typeof ObservatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normativa': {
      id: '/normativa'
      path: '/normativa'
      fullPath: '/normativa'
      preLoaderRoute: typeof NormativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convocatorias': {
      id: '/convocatorias'
      path: '/convocatorias'
      fullPath: '/convocatorias'
      preLoaderRoute: typeof ConvocatoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas/': {
      id: '/mesas/'
      path: '/mesas'
      fullPath: '/mesas/'
      preLoaderRoute: typeof MesasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesas/$slug': {
      id: '/mesas/$slug'
      path: '/mesas/$slug'
      fullPath: '/mesas/$slug'
      preLoaderRoute: typeof MesasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConvocatoriasRoute: ConvocatoriasRoute,
  NormativaRoute: NormativaRoute,
  ObservatorioRoute: ObservatorioRoute,
  RegistroRoute: RegistroRoute,
  MesasSlugRoute: MesasSlugRoute,
  MesasIndexRoute: MesasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
